# Basic
edition    = "2021"
hard_tabs  = true
max_width  = 140
tab_spaces = 4

# Imports
imports_granularity = "Crate"
reorder_imports     = true

# Format comments
comment_width = 120
wrap_comments = true

# Misc
chain_width                = 80
match_arm_blocks           = false
match_block_trailing_comma = true
newline_style              = "Unix"
reorder_impl_items         = true
reorder_modules            = true
use_field_init_shorthand   = true
use_small_heuristics       = "Max"